/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ej6p2lab;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agust
 */
public class ConsultaPrecio extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        //para evitar que puedan editar la tabla
        public boolean isCellEditable(int f, int c) {

            return false;

        }

    };

    /**
     * Creates new form ConsultaPrecio
     */
    public ConsultaPrecio() {
        initComponents();
        armarCabecera();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTprecio1 = new javax.swing.JTextField();
        jTprecio2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Listado por Precio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Entre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("y");

        jTprecio1.setText("0");
        jTprecio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTprecio1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTprecio1KeyTyped(evt);
            }
        });

        jTprecio2.setText("0");
        jTprecio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTprecio2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTprecio2KeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej6p2lab/icons/icons8-magnifying-glass-tilted-right-48.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(jTprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3)
                                .addGap(41, 41, 41)
                                .addComponent(jTprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTprecio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecio1KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar) == false) {

            evt.consume();
        }
    }//GEN-LAST:event_jTprecio1KeyTyped

    private void jTprecio2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecio2KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar) == false) {

            evt.consume();
        }
    }//GEN-LAST:event_jTprecio2KeyTyped

    private void jTprecio1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecio1KeyReleased
        borrarFilas();

        if (jTprecio2.getText().isEmpty() == false && jTprecio1.getText().isEmpty() == false) {

            double preMin = Double.parseDouble(jTprecio1.getText());
            double preMax = Double.parseDouble(jTprecio2.getText());

            for (Producto pe : VistaPrincipal.listaP) {

                if (pe.getPrecio() >= preMin && pe.getPrecio() <= preMax) {

                    modelo.addRow(new Object[]{
                        pe.getCodigo(),
                        pe.getDescripcion(),
                        pe.getPrecio(),
                        pe.getRubro(),
                        pe.getStock()

                    });

                }

            }
           
        }

    }//GEN-LAST:event_jTprecio1KeyReleased

    private void jTprecio2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecio2KeyReleased
        borrarFilas();

        if (jTprecio2.getText().isEmpty() == false && jTprecio1.getText().isEmpty() == false) {

            double preMin = Double.parseDouble(jTprecio1.getText());
            double preMax = Double.parseDouble(jTprecio2.getText());

            for (Producto p : VistaPrincipal.listaP) {

                if (p.getPrecio() >= preMin && p.getPrecio() <= preMax) {

                    modelo.addRow(new Object[]{
                        p.getCodigo(),
                        p.getDescripcion(),
                        p.getPrecio(),
                        p.getRubro(),
                        p.getStock()

                    });

                }
            }
        }
    }//GEN-LAST:event_jTprecio2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTprecio1;
    private javax.swing.JTextField jTprecio2;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {

        modelo.addColumn("codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Categoria");
        modelo.addColumn("Stock");
        jTable1.setModel(modelo);

    }

    private void borrarFilas() {

        int filas = jTable1.getRowCount() - 1;
        for (; filas >= 0; filas--) {
            modelo.removeRow(filas);
        }

    }

}
